### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by cfz1998** [JanaSperschneider/ApoplastP#5]
Hi @JanaSperschneider !
I'm using ApoplastP for prediction. But I get an error:
```
python /data/chaofan/software/ApoplastP/Scripts/ApoplastP.py -i ../02.assemble_res/CCA295.pep -o CCA295.apop
-----------------

ApoplastP is running for 14326 proteins given in FASTA file ../02.assemble_res/CCA295.pep

-----------------
Calculate statistics of protein properties
Traceback (most recent call last):
  File "/data/chaofan/software/ApoplastP/Scripts/ApoplastP.py", line 213, in <module>
    main()
  File "/data/chaofan/software/ApoplastP/Scripts/ApoplastP.py", line 171, in main
    out.writelines(functions.short_output(predictions))
TypeError: a bytes-like object is required, not 'str'
```

How to fix it? Maybe replace "wb" with "w" in the line 164 in `ApoplastP.py `?

Thank you for your reply.

**Comment by JanaSperschneider** [comment]
Hi, 
can you tell me which version of Python you are using? I just ran ApoplastP under Python 3.x and I don't get the error message.

Can you please run the test command (Testing.fasta is provided with ApoplastP) and see if it works?
python ApoplastP.py -i Testing.fasta

I suspect it is either a problem with the Python version or the input FASTA file.

Thanks a lot!
Jana

**Comment by jd3234** [comment]
.Hi,
I am also getting the same error. I am using python 3.12.1 and biopython 1.83. I tested with the fasta you provide with ApoplastP.

**Comment by JanaSperschneider** [comment]
Thanks for clarifying that the problem occurs only with the -o parameter!
Code is updated now (changed 'wb' to 'w' in line 165).
